[package]
name = "lamda_red"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
rand = "0.8.0"
quick-xml = "0.36.1"
serde = { version = "1.0", features = ["derive"] }
cairo-rs = "0.20.1"